### ISSUE TITLE
question about scan.yaml

### ISSUE THREAD

**Issue by philip-zhang-999** [daviddmc/SVoRT#6]
Hello, thanks for your work about svr.
But i have some questions about details in scan.yaml.
I wonder what's the true and detailed meaning of the following parameters in scan.yaml:
resolution_slice_fac: 1.25
resolution_slice_max: 1.5
min_num_stack: 3
max_num_stack: 3
txy: 3
prob_void:  0.03
prob_motion: 0.00
And why there are two values in slice_thickness like [2.5,3.5]？
Is the first one represent slice thickness and the second one represent spacing between slice?
Thank in advance for your help!

**Comment by daviddmc** [comment]
Hi, I added some comments to the yaml file. (see this commit 4c4babbd110df86a4b19394f5be2480e72134fac)
Let me know if you still have questions.
