### ISSUE TITLE
Data simulation

### ISSUE THREAD

**Issue by malaifa** [daviddmc/SVoRT#7]
Hi, it would be nice to have the motion simulation code, thanks!

**Comment by daviddmc** [comment]
Hi,

The code for motion simulation is in
https://github.com/daviddmc/SVoRT/blob/main/src/data/scan.py
https://github.com/daviddmc/SVoRT/blob/main/src/data/fetal_motion.py

If what you mean is how to generate the motion trajectories. You may find the code at 
https://github.com/daviddmc/SVoRT/blob/main/dataset/gen_traj.py
The keypoint data that we used are in 
https://github.com/daviddmc/fetal-motion/tree/main/data
